#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace

# 대충 웹UI 레포지토리와 수정한 소스로부터 바뀐 점을 vscode 로 여는 스크립트

cd "$(dirname "$0")"

target="${1#*/}"

code --diff "repository/$target" "patch/$target"